language: php

php:
  - 7.0
  - 7.1

before_script:
 - composer self-update
 - composer install
 - composer suggests | xargs -i composer require {}

script:
 - php ./vendor/bin/phpunit -c phpunit.xml.dist
